### ISSUE TITLE
PI identifier box doesn't show the selected PI

### ISSUE THREAD

**Issue by ewnash** [nikantonelli/WorkItemsForInitiative#2]
Select a portfolio item, charts load as expected but the label box above the chart shows no PI selected and on reopening the selection dialog, the specified PI is no longer selected. 

![image](https://user-images.githubusercontent.com/24457502/52720361-17dfe280-2f6d-11e9-8144-8cbebb17797b.png)

**Comment by ewnash** [comment]
Clarified- this issue only occurs if one or more of the selected top-level portfolio items is outside the current project scope.

**Comment by nikantonelli** [comment]
@ewnash , I forgot to build and upload the compiled files when I did the update for this problem last year. 
The update was to set the correct data context for the selector. Hopefully, you cannot select things that are out of scope of the tree drawing box.

I have added them now. Try downloading and using the new files in the deploy directory.

**Comment by nikantonelli** [comment]
@ewnash I forgot to update the files in the deploy directory for the change I did last year. The fix was to set the data context for the selector so that you can only see the things that are useable be the rest of the code.

Try downloading the code again and trying.

**Comment by ewnash** [comment]
Sorry @nikantonelli, meant to get back sooner. The fix works as expected, all good now. Thanks!
